config/routes.rb
HomeDashBoard::Application.routes.draw do
  resources :payees

  resources :payment_categories

  root to: 'application#index'

end

app/models/payee.rb
class Payee < ActiveRecord::Base
end

app/models/payment_category.rb
class PaymentCategory < ActiveRecord::Base
  has_many :children, class_name: 'PaymentCategory', foreign_key: :payment_category_id, dependent: :destroy
  belongs_to :parent, class_name: 'PaymentCategory', foreign_key: :payment_category_id

  scope :first_level, -> { where(payment_category_id: nil) }
  scope :get_all, -> { where('1=1') }

  def self.level(level=nil)
    self.where(payment_category_id: level).load
  end

  def build_tree
    upper = self
    output = []
    while upper != nil do
      output.prepend(upper)
      upper = upper.parent
    end
    output
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/payees_controller.rb
class PayeesController < ApplicationController
  before_action :set_payee, only: [:show, :edit, :update, :destroy]

  # GET /payees
  # GET /payees.json
  def index
    @payees = Payee.all
  end

  # GET /payees/1
  # GET /payees/1.json
  def show
  end

  # GET /payees/new
  def new
    @payee = Payee.new
  end

  # GET /payees/1/edit
  def edit
  end

  # POST /payees
  # POST /payees.json
  def create
    @payee = Payee.new(payee_params)

    respond_to do |format|
      if @payee.save
        format.html { redirect_to @payee, notice: 'Payee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payee }
      else
        format.html { render action: 'new' }
        format.json { render json: @payee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payees/1
  # PATCH/PUT /payees/1.json
  def update
    respond_to do |format|
      if @payee.update(payee_params)
        format.html { redirect_to @payee, notice: 'Payee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payees/1
  # DELETE /payees/1.json
  def destroy
    @payee.destroy
    respond_to do |format|
      format.html { redirect_to payees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payee
      @payee = Payee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payee_params
      params[:payee]
    end
end

app/controllers/payment_categories_controller.rb
class PaymentCategoriesController < ApplicationController
  before_action :set_payment_category, only: [:show, :edit, :update, :destroy]

  # GET /payment_categories
  # GET /payment_categories.json
  def index
    @payment_categories = PaymentCategory.level(params[:level])
  end

  # GET /payment_categories/1
  # GET /payment_categories/1.json
  def show
  end

  # GET /payment_categories/new
  def new
    @payment_category = PaymentCategory.new
  end

  # GET /payment_categories/1/edit
  def edit
  end

  # POST /payment_categories
  # POST /payment_categories.json
  def create
    @payment_category = PaymentCategory.new(payment_category_params)

    respond_to do |format|
      if @payment_category.save
        format.html { redirect_to @payment_category, notice: 'Payment category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_categories/1
  # PATCH/PUT /payment_categories/1.json
  def update
    respond_to do |format|
      if @payment_category.update(payment_category_params)
        format.html { redirect_to @payment_category, notice: 'Payment category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_categories/1
  # DELETE /payment_categories/1.json
  def destroy
    @payment_category.destroy
    respond_to do |format|
      format.html { redirect_to payment_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_category
      @payment_category = PaymentCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_category_params
      params.require(:payment_category).permit(:title, :description, :payment_category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payees_helper.rb
module PayeesHelper
end

app/helpers/payment_categories_helper.rb
module PaymentCategoriesHelper
end

app/views/application/index.html.erb
Hello world!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HomeDashBoard" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">HomeDashBoard</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag :application %>

  </body>
</html>

app/views/payees/_form.html.erb
<%= form_for @payee, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :payment_category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :payment_category_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                payees_path, :class => 'btn' %>
  </div>
<% end %>

app/views/payees/edit.html.erb
<%- model_class = Payee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payees/index.html.erb
<%- model_class = Payee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:payment_category_id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @payees.each do |payee| %>
      <tr>
        <td><%= link_to payee.id, payee_path(payee) %></td>
        <td><%= payee.payment_category_id %></td>
        <td><%= payee.title %></td>
        <td><%=l payee.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_payee_path(payee), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      payee_path(payee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_payee_path,
            :class => 'btn btn-primary' %>

app/views/payees/new.html.erb
<%- model_class = Payee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payees/show.html.erb
<%- model_class = Payee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:payment_category_id) %>:</strong></dt>
  <dd><%= @payee.payment_category_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @payee.title %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              payees_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_payee_path(@payee), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              payee_path(@payee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/payment_categories/_form.html.erb
<%= form_for @payment_category, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :payment_category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :payment_category_id, PaymentCategory.get_all.collect {|p| [ p.title, p.id ] }, include_blank: 'Select', selected: params[:level] %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                payment_categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/payment_categories/edit.html.erb
<%- model_class = PaymentCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payment_categories/index.html.erb
<%- model_class = PaymentCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<ul class="breadcrumb">
  <li><%= link_to "Root", payment_categories_path %><span class="divider">/</span></li>
  <% if params[:level] %>
      <% tree = PaymentCategory.find(params[:level]).build_tree
      tree.each do |parent| %>
          <li><%= link_to parent.title, {:action => 'index', :level => parent.id} %> <%= %(<span class="divider">/</span>).html_safe unless parent == tree.last %></li>
      <% end %>
  <% end %>
</ul>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th style="width:55%;"><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @payment_categories.each do |payment_category| %>
      <tr>
        <td><%= link_to payment_category.id, payment_category.children.size > 0 ? {:action => 'index', :level => payment_category.id} : payment_category_path(payment_category) %></td>
        <td><%= link_to payment_category.title, payment_category.children.size > 0 ? {:action => 'index', :level => payment_category.id} : payment_category_path(payment_category) %></td>
        <td><%=t payment_category.created_at %></td>
        <td>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_payment_category_path(payment_category), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      payment_category_path(payment_category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <%= link_to t('.new_sub', :default => t("helpers.links.new_sub")),
                      new_payment_category_path(:level => payment_category.id), :class => 'btn btn-mini btn-success' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_payment_category_path,
            :class => 'btn btn-primary' %>

app/views/payment_categories/new.html.erb
<%- model_class = PaymentCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payment_categories/show.html.erb
<%- model_class = PaymentCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @payment_category.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @payment_category.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              payment_categories_path(:level => @payment_category.payment_category_id), :class => 'btn'  %>

  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_payment_category_path(@payment_category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              payment_category_path(@payment_category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <%= link_to t('.new_sub', :default => t("helpers.links.new_sub")),
              new_payment_category_path(:level => @payment_category.id), :class => 'btn btn-success' %>
</div>